services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  B13\Proxycachemanager\ResourceStorageOperations\:
    resource: '../Classes/ResourceStorageOperations/*'

  B13\Proxycachemanager\ResourceStorageOperations\Listener\BeforeFileDeleted:
    tags:
      - name: event.listener
        identifier: 'b13-proxycachemanager-beforeFileDeleted'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileDeletedEvent
  B13\Proxycachemanager\ResourceStorageOperations\Listener\BeforeFileMoved:
    tags:
      - name: event.listener
        identifier: 'b13-proxycachemanager-beforeFileMoved'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileMovedEvent
  B13\Proxycachemanager\ResourceStorageOperations\Listener\BeforeFileRenamed:
    tags:
      - name: event.listener
        identifier: 'b13-proxycachemanager-beforeFileRenamed'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileRenamedEvent
  B13\Proxycachemanager\ResourceStorageOperations\Listener\BeforeFileReplaced:
    tags:
      - name: event.listener
        identifier: 'b13-proxycachemanager-beforeFileReplaced'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileReplacedEvent
  B13\Proxycachemanager\ResourceStorageOperations\Listener\BeforeFolderDeleted:
    tags:
      - name: event.listener
        identifier: 'b13-proxycachemanager-beforeFolderDeleted'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFolderDeletedEvent
  B13\Proxycachemanager\ResourceStorageOperations\Listener\BeforeFolderMoved:
    tags:
      - name: event.listener
        identifier: 'b13-proxycachemanager-beforeFolderMoved'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFolderMovedEvent
  B13\Proxycachemanager\ResourceStorageOperations\Listener\BeforeFolderRenamed:
    tags:
      - name: event.listener
        identifier: 'b13-proxycachemanager-beforeFolderRenamed'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFolderRenamedEvent

  B13\Proxycachemanager\ResourceStorageOperations\Listener\AfterFileAdded:
    tags:
      - name: event.listener
        identifier: 'b13-proxycachemanager-afterFileAdded'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileAddedEvent

  b13.bunnynet.guzzle_client:
    class: GuzzleHttp\Client
    lazy: true
    arguments:
      $config:
        base_uri: 'https://api.bunny.com/purge/'
        headers:
          AccessKey: '%env(default::string:BUNNY_ACCESSKEY_TOKEN)%'

  B13\Proxycachemanager\Provider\BunnyNetProxyProvider:
    public: true
    arguments:
      $client: '@b13.bunnynet.guzzle_client'
      $sites: '@=service("TYPO3\\CMS\\Core\\Site\\SiteFinder").getAllSites()'
